version: '3.4'

services:
  ara.influxdb.webapi.tool:
    image: 'ara.influxdb.webapi.tool:latest'
    restart: always
    container_name: ara.influxdb.webapi.tool
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - /app/app.proxy.Web.Host/bin/Release/net5.0/wwwroot:/var/docker_volumes/app.proxy/wwwroot
    ports:
      - 5200:80
    networks:
      - ara-network

networks:
  ara-network:
    external: true
